package main

var levels = [][]Vial{
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{},
	[]Vial{
		{DBLUE, DGREEN, LBLUE, LBLUE},
		{VIOLET, PINK, LGREEN, GRAY},
		{ORANGE, VIOLET, RED, BROWN},
		{ORANGE, PINK, RED, ORANGE},
		{DGREEN, RED, YELLOW, DBLUE},
		{YELLOW, DGREEN, BROWN, DGREEN},
		{BROWN, VIOLET, RED, BGREEN},
		{BGREEN, VIOLET, PINK, BGREEN},
		{LGREEN, GRAY, LBLUE, DBLUE},
		{BROWN, YELLOW, GRAY, LGREEN},
		{GRAY, YELLOW, BGREEN, DBLUE},
		{LGREEN, LBLUE, PINK, ORANGE},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{VIOLET, RED, BGREEN, PINK},
		{PINK, LGREEN, DBLUE, DBLUE},
		{DBLUE, LBLUE, LBLUE, GRAY},
		{PINK, LGREEN, BGREEN, LGREEN},
		{GRAY, VIOLET, ORANGE, ORANGE},
		{PINK, RED, ORANGE, LGREEN},
		{RED, BGREEN, GRAY, GRAY},
		{ORANGE, VIOLET, RED, BGREEN},
		{VIOLET, DBLUE, LBLUE, LBLUE},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{BGREEN, GRAY, ORANGE, YELLOW},
		{RED, VIOLET, LGREEN, LBLUE},
		{LGREEN, PINK, BGREEN, VIOLET},
		{YELLOW, PINK, RED, BROWN},
		{LGREEN, DBLUE, BROWN, VIOLET},
		{LGREEN, GRAY, VIOLET, YELLOW},
		{ORANGE, GRAY, LBLUE, DGREEN},

		{RED, DGREEN, LBLUE, PINK},
		{DBLUE, DBLUE, LBLUE, BGREEN},
		{DGREEN, BROWN, PINK, ORANGE},
		{GRAY, BGREEN, YELLOW, ORANGE},
		{RED, BROWN, DGREEN, DBLUE},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{LBLUE, DGREEN, RED, LGREEN},
		{LBLUE, LBLUE, DGREEN, PINK},
		{RED, RED, DGREEN, VIOLET},
		{DBLUE, PINK, ORANGE, GRAY},
		{PINK, RED, GRAY, VIOLET},
		{LGREEN, GRAY, VIOLET, DBLUE},

		{ORANGE, VIOLET, DGREEN, DBLUE},
		{ORANGE, GRAY, ORANGE, LGREEN},
		{PINK, LGREEN, DBLUE, LBLUE},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{LBLUE, ORANGE, BROWN, GRAY},
		{GRAY, YELLOW, LGREEN, VIOLET},
		{ORANGE, BGREEN, PINK, LBLUE},
		{DBLUE, YELLOW, RED, YELLOW},
		{BROWN, VIOLET, ORANGE, YELLOW},
		{DGREEN, LGREEN, BGREEN, DGREEN},
		{BGREEN, DBLUE, RED, DBLUE},

		{BROWN, LGREEN, BROWN, RED},
		{PINK, LGREEN, LBLUE, VIOLET},
		{VIOLET, BGREEN, ORANGE, PINK},
		{GRAY, PINK, DGREEN, DGREEN},
		{GRAY, RED, LBLUE, DBLUE},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{LBLUE, ORANGE, BROWN, GRAY},
		{GRAY, YELLOW, LGREEN, VIOLET},
		{ORANGE, BGREEN, PINK, LBLUE},
		{DBLUE, YELLOW, RED, YELLOW},
		{BROWN, VIOLET, ORANGE, YELLOW},
		{DGREEN, LGREEN, BGREEN, DGREEN},
		{BGREEN, DBLUE, RED, DBLUE},

		{BROWN, LGREEN, BROWN, RED},
		{PINK, LGREEN, LBLUE, VIOLET},
		{VIOLET, BGREEN, ORANGE, PINK},
		{GRAY, PINK, DGREEN, DGREEN},
		{GRAY, RED, LBLUE, DBLUE},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{DBLUE, ORANGE, DGREEN, YELLOW},
		{DGREEN, PINK, LGREEN, BGREEN},
		{RED, LBLUE, VIOLET, YELLOW},
		{VIOLET, ORANGE, LBLUE, DGREEN},
		{DBLUE, PINK, GRAY, BGREEN},
		{BGREEN, BROWN, YELLOW, DGREEN},
		{RED, PINK, LBLUE, BROWN},

		{GRAY, BGREEN, DBLUE, ORANGE},
		{LGREEN, LGREEN, GRAY, YELLOW},
		{BROWN, PINK, LGREEN, LBLUE},
		{GRAY, RED, VIOLET, BROWN},
		{ORANGE, VIOLET, DBLUE, RED},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{YELLOW, ORANGE, DBLUE, YELLOW},
		{LGREEN, YELLOW, PINK, GRAY},
		{DBLUE, PINK, DBLUE, BGREEN},
		{GRAY, RED, YELLOW, DGREEN},
		{LGREEN, GRAY, VIOLET, RED},
		{ORANGE, DBLUE, BROWN, BGREEN},
		{DGREEN, LBLUE, RED, VIOLET},

		{BGREEN, LBLUE, PINK, BROWN},
		{LGREEN, PINK, DGREEN, BROWN},
		{BROWN, VIOLET, LBLUE, DGREEN},
		{GRAY, ORANGE, BGREEN, LGREEN},
		{LBLUE, ORANGE, VIOLET, RED},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{DBLUE, BGREEN, VIOLET, RED},
		{PINK, LGREEN, RED, LGREEN},
		{LBLUE, ORANGE, ORANGE, VIOLET},
		{DBLUE, VIOLET, RED, GRAY},
		{BGREEN, PINK, LBLUE, LBLUE},
		{PINK, ORANGE, DBLUE, VIOLET},

		{BGREEN, PINK, LGREEN, GRAY},
		{ORANGE, BGREEN, RED, DBLUE},
		{LBLUE, GRAY, LGREEN, GRAY},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{ORANGE, RED, BROWN, BROWN},
		{LGREEN, PINK, PINK, BROWN},
		{VIOLET, BGREEN, LGREEN, DBLUE},
		{RED, GRAY, BROWN, ORANGE},
		{RED, DBLUE, BGREEN, LGREEN},
		{VIOLET, LBLUE, BGREEN, VIOLET},
		{LBLUE, DBLUE, DGREEN, LGREEN},

		{YELLOW, LBLUE, YELLOW, GRAY},
		{DGREEN, YELLOW, GRAY, ORANGE},
		{BGREEN, RED, YELLOW, ORANGE},
		{GRAY, DGREEN, DBLUE, VIOLET},
		{DGREEN, LBLUE, PINK, PINK},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{LBLUE, PINK, LBLUE, DBLUE},
		{LBLUE, LGREEN, LGREEN, VIOLET},
		{RED, RED, PINK, RED},
		{ORANGE, GRAY, GRAY, VIOLET},
		{LBLUE, PINK, GRAY, VIOLET},
		{BGREEN, RED, GRAY, BGREEN},

		{DBLUE, ORANGE, BGREEN, LGREEN},
		{LGREEN, PINK, ORANGE, DBLUE},
		{ORANGE, DBLUE, BGREEN, VIOLET},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
	[]Vial{
		{LBLUE, VIOLET, DGREEN, BGREEN},
		{DBLUE, BGREEN, GRAY, PINK},
		{DBLUE, LBLUE, DBLUE, LBLUE},
		{RED, ORANGE, VIOLET, DGREEN},
		{BGREEN, ORANGE, RED, LBLUE},
		{RED, YELLOW, ORANGE, DGREEN},
		{LGREEN, LGREEN, RED, VIOLET},

		{LGREEN, GRAY, LGREEN, BGREEN},
		{YELLOW, DBLUE, BROWN, YELLOW},
		{BROWN, VIOLET, ORANGE, PINK},
		{GRAY, BROWN, YELLOW, GRAY},
		{PINK, BROWN, DGREEN, PINK},
		{AIR, AIR, AIR, AIR},
		{AIR, AIR, AIR, AIR},
	},
}
